#version: "3"
#
#services:
#  kafka:
#    image: bitnami/kafka
#    restart: always
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    ports:
#    - 6379:6379
#
#  botionServer:
#    build: botionServer
#    restart: always
#    depends_on:
#      - registry
#    environment:
#      REGISTRY_HOST: registry
#      REDIS_HOST: redis
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    ports:
#      - 8100:8100
#
version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  botionServer:
    build: botionServer
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_CONNECT=kafka:9092
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8080:8080

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local